version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
    # We no longer need 'depends_on: mongodb' because the DB is now in the cloud

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

# We can remove the local mongodb service entirely to save AWS memory/CPU
