version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # This will load EVERYTHING from your .env file automatically
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
